### ISSUE TITLE
Error parsing example 3: Betrachtungszeitraum is unknown

### ISSUE THREAD

**Issue by xinsight** [mio42-GmbH/Validierungspaket-MIO-DiGA-Toolkit#3]
I'm seeing the following validation error when attempting to validate the included example 3:

```
$ java -jar validator_cli_5.6.76.jar Example/REAL_EXAMPLE_3_KBV_PR_MIO_DIGA_Bundle.xml \
-ig "hl7.fhir.core#4.0.1" -ig "./KBV-Base" -ig "./HL7-Base-de" -ig ./FHIR-Specification  -verbose 
...
*FAILURE*: 1 errors, 23 warnings, 27 notes
  Error @ Bundle.entry[0].resource.ofType(Composition).extension[0] (line 32, col111): 
The extension https://fhir.kbv.de/StructureDefinition/KBV_EX_MIO_DIGA_Betrachtungszeitraum is unknown, 
and not allowed here
...
```

The structure definition for a MIO `Composition` clearly requires a `betrachtungszeitraum` extension with a period, so I'm not sure what the problem is.

<img width="579" alt="extension-period" src="https://user-images.githubusercontent.com/465971/223140325-8c1fb248-5e59-4423-aa6b-cb034c3e6d26.png">

Is the FHIR validator broken? (I get the same error with versions `5.6.97` and `5.6.76`.)

Any ideas?

**Comment by xinsight** [comment]
Ah, i was missing the `-recurse` option. With recurse, i see the parse exceptions mentioned in #2 but the error about the `betrachtungszeitraum` extension is resolved.

**Comment by mio42** [comment]
Happy to see that you found the solution :)
Feel free to reach out in case that there are further issues!
